# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('type_of_leave', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('till_date', models.DateField()),
                ('acad_pf', models.IntegerField()),
                ('admin_pf', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('purpose', models.CharField(max_length=500)),
                ('date_of_app', models.DateField()),
                ('is_station', models.BooleanField(default='false')),
                ('pf', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leave_credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual', models.IntegerField()),
                ('restricted', models.IntegerField()),
                ('sp_casual', models.IntegerField()),
                ('earned', models.IntegerField()),
                ('commuted', models.IntegerField()),
                ('vacation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('designation', models.CharField(max_length=50)),
                ('pf', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default='False')),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='leave_credits',
            name='pf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.User'),
        ),
    ]
