# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='application',
        ),
        migrations.RemoveField(
            model_name='leave_credits',
            name='pf',
        ),
        migrations.DeleteModel(
            name='Leave_credits',
        ),
    ]
