# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20170826_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('FA', 'Finance and Accounts'), ('EST', 'Establishment'), ('Academics', 'Academics'), ('CC', 'Computer Center'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('ME', 'ME'), ('Design', 'Design'), ('Mechatronics', 'Mechatronics'), ('NS', 'Natural Science'), ('PC', 'Placement Cell'), ('IWD', 'IWD'), ('R&D', 'Office of The Dean R&D'), ('Directorate', 'Directorate'), ('Library', 'Library'), ('P&D', 'Office of The Dean P&D'), ('Student Affairs', 'Student Affairs'), ('GA', 'General Administration'), ('RO', 'Registrar Office'), ('PS', 'Purchase and Store'), ('Workshop', 'Workshop'), ('EST-PS', 'Establishment & P&S'), ('FA-GA', 'F&A & GA'), ('Security', 'Security and Central Mess'), ('RTI', 'Establishment, RTI and Rajbhasha')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('SA', 'Senior Assistant'), ('JA', 'Junior Assistant'), ('ST', 'Senior Technician'), ('JT', 'Junior Technician'), ('JE', 'Junior Engineer'), ('Driver', 'Driver'), ('JS', 'Junior Superintendent'), ('EXE', 'Executive Engineer (Civil)'), ('AR', 'Assistant Registrar'), ('DR', 'Deputy Registrar'), ('P', 'Professor'), ('AP', 'Assistant Professor'), ('AsP', 'Associate Professor'), ('RE', 'Research Engineer'), ('AP', 'Assistant Professor'), ('D', 'Director')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=123, max_length=1000),
        ),
    ]
