# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20170830_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='department',
            field=models.CharField(choices=[('FA', 'Finance and Accounts'), ('EST', 'Establishment'), ('Academics', 'Academics'), ('CC', 'Computer Center'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('ME', 'ME'), ('Design', 'Design'), ('Mechatronics', 'Mechatronics'), ('NS', 'Natural Science'), ('PC', 'Placement Cell'), ('IWD', 'IWD'), ('R&D', 'Office of The Dean R&D'), ('Directorate', 'Directorate'), ('Library', 'Library'), ('P&D', 'Office of The Dean P&D'), ('Student Affairs', 'Student Affairs'), ('GA', 'General Administration'), ('RO', 'Registrar Office'), ('PS', 'Purchase and Store'), ('Workshop', 'Workshop'), ('EST-PS', 'Establishment & P&S'), ('FA-GA', 'F&A & GA'), ('Security', 'Security and Central Mess'), ('RTI', 'Establishment, RTI and Rajbhasha'), ('RSPC', 'RSPC')], default='CSE', max_length=50),
        ),
    ]
