# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_auto_20170902_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenthead',
            name='temp',
        ),
    ]
