# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_departmenthead_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
