# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_auto_20170902_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='from_d',
            field=models.DateField(null=True),
        ),
    ]
