# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0002_auto_20170827_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='pf',
            new_name='pf_in',
        ),
        migrations.AddField(
            model_name='application',
            name='pf_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='sanction_cl_rh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_rh', to='basic.User'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='sanction_others',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='basic.User'),
        ),
    ]
