# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0003_auto_20170827_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pf_out',
            field=models.IntegerField(),
        ),
    ]
