# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0006_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='st_from_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 16, 22, 50, 796501)),
        ),
        migrations.AddField(
            model_name='application',
            name='st_till_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 16, 22, 50, 796526)),
        ),
    ]
