# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0007_auto_20170829_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='st_from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='st_till_date',
            field=models.DateField(),
        ),
    ]
