# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0009_auto_20170829_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pf_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_in', to='basic.User'),
        ),
    ]
