# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0010_auto_20170829_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='type_of_leave',
            field=models.IntegerField(),
        ),
    ]
