# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0014_auto_20170831_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_credits',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
