# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0015_leave_credits_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='date',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='pf_reciever',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='pf_sender',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='response',
        ),
        migrations.AddField(
            model_name='inbox',
            name='acad_resp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inbox',
            name='admin_respo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inbox',
            name='ap_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leavemodule.Application'),
        ),
    ]
