# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20170831_1805'),
        ('leavemodule', '0016_auto_20170901_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='pf_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.User'),
        ),
        migrations.AlterField(
            model_name='application',
            name='pf_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_in', to='basic.User'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='ap_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leavemodule.Application'),
        ),
    ]
