# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20170831_1805'),
        ('leavemodule', '0019_auto_20170901_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='acad_res_pf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acad_res_pf', to='basic.User'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='admin_res_pf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_res_pf', to='basic.User'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='ap_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leavemodule.Application'),
        ),
    ]
